### ISSUE TITLE
Criar solução Ptich Canvas

### ISSUE THREAD

**Issue by jackson-roberio** [Raidro/Rentech#5]
# Resumo
De acordo com material repassado pelo professor Romão, criar **Ptich canvas** de acordo com nossa solução proposta.

# TODO
- [x] colocar o modelo de Pitch Canvas
- [ ] Criar o Pitch Canvas

**Comment by lionelle234** [comment]
Fiz um esboço de 3 das 9 partes do Pitch Canvas. Acham bom ou falta algo? E dos 6 restantes quais seriam os mais relevantes? Não sei bem como ficaria a parte de ''Histórico'' e ''Mercado''
[Pitch.docx](https://github.com/Raidro/Rentech/files/5368203/Pitch.docx)

**Comment by Raidro** [comment]
> Fiz um esboço de 3 das 9 partes do Pitch Canvas. Acham bom ou falta algo? E dos 6 restantes quais seriam os mais relevantes? Não sei bem como ficaria a parte de ''Histórico'' e ''Mercado''
> [Pitch.docx](https://github.com/Raidro/Rentech/files/5368203/Pitch.docx)

@lionelle234 eu vou te ajudar a fazer esse pq ele tem muita coisa, vou fazer os outros 6, blz? já vou colocar o que vc escreveu em um README
